In [1]:
import pandas as pd

In [5]:
ls

 Volume in drive C is OSDisk
 Volume Serial Number is EC00-BE2C

 Directory of C:\Users\mn14tm\Code\Lifetmm\lifetmm\Data

15/02/2017  17:56    <DIR>          .
15/02/2017  17:56    <DIR>          ..
15/02/2017  17:56    <DIR>          .ipynb_checkpoints
15/02/2017  17:29            48,005 log.txt
05/05/2016  15:11             1,643 Screening.CSV
15/02/2017  17:47               464 T-series_fp.csv
15/02/2017  17:56                72 Untitled.ipynb
               4 File(s)         50,184 bytes
               3 Dir(s)  50,035,474,432 bytes free

In [10]:
a = pd.read_csv('./Screening.CSV')
a.set_index('Sample ID')

,StdOrder,RunOrder,CenterPt,Blocks,Er,Yb,Deposition Time,Pressure,Lifetime_100us_pump,Reflection (%),Transmission (%),n,d
Sample ID,,,,,,,,,,,,,
T2,5,1,1,1,-1,-1,1,1,12.478841,0.173160,92.644947,1.5881,1.0821
T4,4,2,1,1,1,1,-1,-1,1.541386,0.240195,90.473665,1.6868,0.6425
T5,1,3,1,1,-1,-1,-1,-1,12.971973,0.171110,92.162333,1.5801,0.7351
T6,8,4,1,1,1,1,1,1,10.131770,0.305797,90.872803,1.6613,1.2078
T7,2,5,1,1,1,-1,-1,1,10.870046,0.138847,93.050809,1.6191,0.4802
T8,7,6,1,1,-1,1,1,-1,11.664499,0.190927,91.965506,1.6297,1.7061
T10,11,7,0,1,0,0,0,0,10.742143,0.107681,91.548103,1.6181,0.6988
T11,10,8,0,1,0,0,0,0,10.654805,0.096244,91.689184,1.6158,0.6819
T14,6,9,1,1,1,-1,1,-1,10.407751,1.346310,91.650510,NaN,NaN
T15,3,10,1,2,-1,1,-1,1,11.808809,0.397868,93.304663,1.6072,0.9697
T16,9,11,0,2,0,0,0,0,11.256504,0.830331,92.805359,1.6119,1.0520
T20,17,12,1,2,1,1,1,-1,12.945338,5.109873,89.686774,NaN,NaN
T21,18,13,1,2,-1,-1,-1,1,12.251599,4.614486,91.920114,1.6058,1.1967
T22,14,14,1,2,-1,1,1,1,12.136043,0.213593,92.389736,1.6185,1.5517
T23,20,15,0,2,0,0,0,0,11.186238,0.348863,92.678823,1.6132,1.0751
T24,15,16,1,2,-1,-1,1,-1,12.323310,0.588810,92.363893,1.6048,2.3665
T25,12,17,1,2,1,1,-1,1,10.117429,4.609705,91.828963,1.6791,1.4214
T26,13,18,1,2,1,-1,1,1,11.792269,0.126496,91.972316,1.6308,2.0468
T27,16,19,1,2,1,-1,-1,-1,10.847124,11.094721,91.921055,1.6310,1.7988
T28,19,20,1,2,-1,1,-1,-1,12.066991,0.438708,91.623385,1.6308,2.5432
T29,21,21,0,2,0,0,0,0,11.397184,0.213317,92.310784,1.6026,0.8407

In [6]:
b = pd.read_csv('./T-series_fp.csv')

In [9]:
pd.concat([a, b])

,Blocks,CenterPt,Deposition Time,Er,Lifetime_100us_pump,Pressure,Purcell Factor,Reflection (%),RunOrder,Sample ID,StdOrder,Transmission (%),WG Modes Air,WG Modes Canola,Yb,d,n
0,1.0,1.0,1.0,-1.0,12.478841,1.0,NaN,0.173160,1.0,T2,5.0,92.644947,NaN,NaN,-1.0,1.0821,1.5881
1,1.0,1.0,-1.0,1.0,1.541386,-1.0,NaN,0.240195,2.0,T4,4.0,90.473665,NaN,NaN,1.0,0.6425,1.6868
2,1.0,1.0,-1.0,-1.0,12.971973,-1.0,NaN,0.171110,3.0,T5,1.0,92.162333,NaN,NaN,-1.0,0.7351,1.5801
3,1.0,1.0,1.0,1.0,10.131770,1.0,NaN,0.305797,4.0,T6,8.0,90.872803,NaN,NaN,1.0,1.2078,1.6613
4,1.0,1.0,-1.0,1.0,10.870046,1.0,NaN,0.138847,5.0,T7,2.0,93.050809,NaN,NaN,-1.0,0.4802,1.6191
5,1.0,1.0,1.0,-1.0,11.664499,-1.0,NaN,0.190927,6.0,T8,7.0,91.965506,NaN,NaN,1.0,1.7061,1.6297
6,1.0,0.0,0.0,0.0,10.742143,0.0,NaN,0.107681,7.0,T10,11.0,91.548103,NaN,NaN,0.0,0.6988,1.6181
7,1.0,0.0,0.0,0.0,10.654805,0.0,NaN,0.096244,8.0,T11,10.0,91.689184,NaN,NaN,0.0,0.6819,1.6158
8,1.0,1.0,1.0,1.0,10.407751,-1.0,NaN,1.346310,9.0,T14,6.0,91.650510,NaN,NaN,-1.0,NaN,NaN
9,2.0,1.0,-1.0,-1.0,11.808809,1.0,NaN,0.397868,10.0,T15,3.0,93.304663,NaN,NaN,1.0,0.9697,1.6072
10,2.0,0.0,0.0,0.0,11.256504,0.0,NaN,0.830331,11.0,T16,9.0,92.805359,NaN,NaN,0.0,1.0520,1.6119
11,2.0,1.0,1.0,1.0,12.945338,-1.0,NaN,5.109873,12.0,T20,17.0,89.686774,NaN,NaN,1.0,NaN,NaN
12,2.0,1.0,-1.0,-1.0,12.251599,1.0,NaN,4.614486,13.0,T21,18.0,91.920114,NaN,NaN,-1.0,1.1967,1.6058
13,2.0,1.0,1.0,-1.0,12.136043,1.0,NaN,0.213593,14.0,T22,14.0,92.389736,NaN,NaN,1.0,1.5517,1.6185
14,2.0,0.0,0.0,0.0,11.186238,0.0,NaN,0.348863,15.0,T23,20.0,92.678823,NaN,NaN,0.0,1.0751,1.6132
15,2.0,1.0,1.0,-1.0,12.323310,-1.0,NaN,0.588810,16.0,T24,15.0,92.363893,NaN,NaN,-1.0,2.3665,1.6048
16,2.0,1.0,-1.0,1.0,10.117429,1.0,NaN,4.609705,17.0,T25,12.0,91.828963,NaN,NaN,1.0,1.4214,1.6791
17,2.0,1.0,1.0,1.0,11.792269,1.0,NaN,0.126496,18.0,T26,13.0,91.972316,NaN,NaN,-1.0,2.0468,1.6308
18,2.0,1.0,-1.0,1.0,10.847124,-1.0,NaN,11.094721,19.0,T27,16.0,91.921055,NaN,NaN,-1.0,1.7988,1.6310
19,2.0,1.0,-1.0,-1.0,12.066991,-1.0,NaN,0.438708,20.0,T28,19.0,91.623385,NaN,NaN,1.0,2.5432,1.6308
20,2.0,0.0,0.0,0.0,11.397184,0.0,NaN,0.213317,21.0,T29,21.0,92.310784,NaN,NaN,0.0,0.8407,1.6026
0,NaN,NaN,NaN,NaN,NaN,NaN,1.009899,NaN,NaN,T10,NaN,NaN,2.0,0.0,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,1.018711,NaN,NaN,T11,NaN,NaN,2.0,0.0,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,0.940783,NaN,NaN,T15,NaN,NaN,2.0,0.0,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,0.922977,NaN,NaN,T16,NaN,NaN,2.0,0.0,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,0.936892,NaN,NaN,T2,NaN,NaN,2.0,0.0,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,0.916036,NaN,NaN,T21,NaN,NaN,2.0,0.0,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,0.924029,NaN,NaN,T22,NaN,NaN,2.0,2.0,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,0.919428,NaN,NaN,T23,NaN,NaN,2.0,0.0,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,0.931351,NaN,NaN,T24,NaN,NaN,4.0,0.0,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,1.065581,NaN,NaN,T25,NaN,NaN,4.0,2.0,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,1.046141,NaN,NaN,T26,NaN,NaN,4.0,2.0,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,1.026655,NaN,NaN,T27,NaN,NaN,4.0,2.0,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,1.064163,NaN,NaN,T28,NaN,NaN,6.0,2.0,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,0.979220,NaN,NaN,T29,NaN,NaN,2.0,0.0,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,1.042423,NaN,NaN,T4,NaN,NaN,2.0,2.0,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,1.036739,NaN,NaN,T5,NaN,NaN,2.0,0.0,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,1.064595,NaN,NaN,T6,NaN,NaN,3.0,2.0,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,1.100267,NaN,NaN,T7,NaN,NaN,2.0,0.0,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,1.010433,NaN,NaN,T8,NaN,NaN,4.0,2.0,NaN,NaN,NaN